from models.model import Model
from tensorflow.keras import Sequential, layers, models
from tensorflow.keras.layers.experimental.preprocessing import Rescaling
from tensorflow.keras.optimizers import RMSprop, Adam

class RandomModel(Model):
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        # very similar to transfered_model.py, the only difference is that you should randomize the weights
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # randomize the weights of the loaded model, possibly by using _randomize_layers
        # use this model by removing the last layer, adding dense layers and an output layer

        
        basemodel = models.load_model("results/basic_model_12_epochs_timestamp_1785540830.keras")
        self._randomize_layers(basemodel)
        for layer in basemodel.layers[:-1]:
            layer.trainable = True

        x = basemodel.get_layer("flatten").output
        x = layers.Dense(18,activation="relu", name="trans_dense")(x)
        x = layers.Dropout(0.3,name="trans_dropout")(x)
        output = layers.Dense(categories_count,activation="softmax",name = "random_output")(x)
        
        self.model = models.Model(inputs=basemodel.input,outputs=output)

    
    def _compile_model(self):
       self.model.compile(
                   optimizer=RMSprop(learning_rate=0.001),
                   loss='categorical_crossentropy',
                   metrics=['accuracy']
               )

    @staticmethod
    def _randomize_layers(model):
       for layer in model.layers:
            if hasattr(layer, "kernel") and hasattr(layer, "kernel_initializer"):
                layer.kernel.assign(
                layer.kernel_initializer(
                    shape=layer.kernel.shape,
                    dtype=layer.kernel.dtype
                )
            )

            if hasattr(layer, "bias") and layer.bias is not None:
                layer.bias.assign(
                layer.bias_initializer(
                    shape=layer.bias.shape,
                    dtype=layer.bias.dtype
                )
            )
            layer.trainable = True
