from models.model import Model
from tensorflow.keras import Sequential, layers, models
from tensorflow.keras.optimizers import RMSprop, Adam
from config import basic_model_path

class TransferedModel(Model):
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # use this model by removing the last layer, adding dense layers and an output layer
        basemodel = models.load_model(basic_model_path)
        for layer in basemodel.layers[:-1]:
            layer.trainable = False
        x = basemodel.get_layer("flatten").output
        x = layers.Dense(18, activation="relu", name="trans_dense")(x)
        x = layers.Dropout(0.3, name="trans_dropout")(x)
        output = layers.Dense(categories_count, activation="softmax", name="transfer_output")(x)

        self.model = models.Model(inputs=basemodel.input, outputs=output)
    
    def _compile_model(self):
        # Your code goes here
        # you have to compile the keras model, similar to the example in the writeup
        self.model.compile(
                    optimizer=RMSprop(learning_rate=0.001),
                    loss='categorical_crossentropy',
                    metrics=['accuracy']
                )
